#!usr/bin/env/python3

# with open('sample.txt') as f:
# 	fp = f.read()
# print(f.closed) # True, becuase the with close the file automatically

# print(f.read()) # try to read it again raises an error because the file is 
				# already closed


# data = list()
# for i in range(11):
# 	user = int(input('Integer: '))

# x = list() 
# for _ in range(3):
# 	user = int(input("int: "))
# 	x.append(user)

# print(sum(x))


